name: PR

on: 
  workflow_dispatch: null
  push: 
    branches: 
      - main
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  Main:
    uses: ./.github/workflows/workflow_a.yml
    secrets: inherit
  TestArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: actions/download-artifacts@v3
        with: 
          name: workflow-${{ github.sha}}
    needs: 
      - Main
        

