name: PR

on: 
  workflow_dispatch: null
  push: 
    branches: 
      - main
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  Main:
    uses: ./workflow_a.yml
    secrets: inherit
        

