name: PR

on: 
  workflow_dispatch: null
  push: 
    branches: 
      - main
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  Main:
    uses: ./.github/workflows/workflow_a.yml
    secrets: inherit
  Test-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: workflow-${{ github.sha}}
      - name: Check files
        run: |
          ls -a
          cat test.txt
    needs: 
      - Main

