# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on: workflow_call
defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo "Test" > test.txt
          cat test.txt
      - name: Upload Artifacts
        uses: actions/upload-artifacts@v3
        with:
          name: workflow-${{ github.sha}}
          path: .
